spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-turbo

    mcp:
      client:
        request-timeout: 60s
        sse:
          connections:
            server1:
              url: http://localhost:9999
    graph:
      nodes:
        node2servers:
          mcp-node:
            - server1