spring:
  datasource:
    url: jdbc:postgresql://${DOCKER_IP}:5432/data_filter?reWriteBatchedInserts=true
    password: postgres
    username: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 550000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v4
      rerank:
        options:
          model: gte-rerank-v2
    vectorstore:
      milvus:
        client:
          host: ${DOCKER_IP}
          port: 19530
        database-name: dataFilter
        embedding-dimension: 1024
        initialize-schema: true
        collection-name: vector_store
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers-config.json
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    async:
      request-timeout: 1000000
  data:
    redis:
      host: ${DOCKER_IP}
      password: redis123
      port: 6379
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 5
        shutdown-timeout: 1000ms
  aliyun:
    bucket-name: spring-ai-alibaba
    region: cn-shenzhen
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    image-dir: user/avatar
    file-dir: user/file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    default-executor-type: batch
  type-handlers-package: alibaba.datafilter.config
logging:
  level:
    alibaba:
      datafilter: debug
server:
  port: 9090