spring:
  datasource:
    url: jdbc:postgresql://10.160.255.223:5432/data_filter
    password: postgres
    username: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 550000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-latest
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      milvus:
        client:
          host: 10.160.255.223
          port: 19530
        database-name: dataFilter
        embedding-dimension: 1024
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: 10.160.255.223
      password: redis123
      lettuce:
        pool:
          max-idle: 10
          max-active: 20
          min-idle: 5
  aliyun:
    bucket-name: spring-ai-alibaba
    region: cn-shenzhen
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    dir: user/avatar/
logging:
  level:
    alibaba:
      datafilter: debug